---
# tips : 在查看配置是否生效前先把相应的plugin先进行下载
root: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  extraFileExtensions:
    - '.vue'
  sourceType: 'module'
  # 允许使用jsx
  ecmaFeatures: true
env:
  browser: true
  node: true
  es6: true
plugins:
  - 'vue'
  - '@typescript-eslint'
  - 'chzky'
settings: {}
extends: []
rules:
  # 变量名允许使用UPPER_CASE和snake_case进行命名
  # class,enum名允许使用StrictPascalCase额河UPPER_CASE进行命名
  # 函数名和参数名允许使用snake_case进行命名
  '@typescript-eslint/naming-convention':
    - 1
    - selector:
        - 'variableLike'
      format:
        - 'snake_case'
      trailingUnderscore: 'allowSingleOrDouble'
    - selector:
        - 'class'
      format:
        - 'StrictPascalCase'
        - 'UPPER_CASE'
      trailingUnderscore: 'allowSingleOrDouble'
    - selector:
        - 'enum'
      format:
        - 'PascalCase'
        - 'UPPER_CASE'
      trailingUnderscore: 'allowSingleOrDouble'
    - selector:
        - 'variable'
      format:
        - 'UPPER_CASE'
        - 'snake_case'
      trailingUnderscore: 'allowSingleOrDouble'
  'chzky/vue-prop-name-check': 1 # prop数据应该使用大驼峰命名
  'chzky/vue-method-name-check': 1 # method方法应该使用蛇形命名
  'chzky/vue-computed-name-check': 1 # 计算属性前面加上`comp_`作为前缀
  'vue/component-name-in-template-casing': # 自定义组件使用大驼峰命名
    - 2
    - 'PascalCase'
  'vue/attribute-hyphenation': # 类名和属性使用单串式命名
    - 2
    - 'always'
  'vue/no-async-in-computed-properties': 2 # 不允许异步的计算属性
  'vue/no-side-effects-in-computed-properties': 2 # 不允许计算属性改变外部值,要想改只能复制到内部修改
  'vue/v-bind-style': # 不能使用[v-bind]代替[:]
    - 2
    - 'shorthand'
  'vue/v-on-style': # 不能使用[v-on]代替[@]
    - 'error'
    - 'shorthand'
  'vue/this-in-template': # template不能使用this
    - 2
    - 'never'
  'vue/no-use-v-if-with-v-for': # 禁止同时出现v-for和v-if
    - 2
    - allowUsingIterationVar: false
  'vue/html-self-closing': # 消除单闭合标签警告问题
    - 2
    - html:
        void: 'always' # 对于Html单标签必须自闭合
        normal: 'never' # 对于Html普通元素不使用自闭合标签
        component: 'always' # 组件如果里面没有内容必须自闭合
      svg: 'always'
      math: 'always'
  'vue/order-in-components': # 如果使用option-api script区域的位置顺序
    - 2
    - order:
        - 'el'
        - 'name'
        - 'key'
        - 'parent'
        - 'functional'
        - - 'delimiters'
          - 'comments'
        - - 'components'
          - 'directives'
          - 'filters'
        - 'extends'
        - 'mixins'
        - - 'provide'
          - 'inject'
        - 'ROUTER_GUARDS'
        - 'layout'
        - 'middleware'
        - 'validate'
        - 'scrollToTop'
        - 'transition'
        - 'loading'
        - 'inheritAttrs'
        - 'model'
        - - 'props'
          - 'propsData'
        - 'emits'
        - 'setup'
        - 'asyncData'
        - 'data'
        - 'fetch'
        - 'head'
        - 'computed'
        - 'watch'
        - 'watchQuery'
        - 'LIFECYCLE_HOOKS'
        - 'methods'
        - - 'template'
          - 'render'
        - 'renderError'
  'vue/attributes-order': # template元素属性的排列顺序
    - 2
    - order:
        - 'CONDITIONALS' # render : such as v-if
        - - 'SLOT'
          - 'DEFINITION'
          - 'LIST_RENDERING'
          - 'CONTENT'
          - 'TWO_WAY_BINDING'
          - 'RENDER_MODIFIERS'
          - 'OTHER_DIRECTIVES'
        - - 'GLOBAL' # props
          - 'ATTR_STATIC'
          - 'UNIQUE'
        - 'ATTR_SHORTHAND_BOOL' # once-prop
        - 'ATTR_DYNAMIC' # v-bind
        - 'EVENTS' # @-any
    alphabetical: false
