# // tips:  用 /* prettier-ignore */ 进行注释, 下行代码将不会进行格式化
# 单行长度
printWidth: 120
# 缩进长度
tabWidth: 2
# 使用空格代替tab缩进
useTabs: false
# 句末使用分号
semi: false
# 使用单引号
singleQuote: true
# 仅在必需时为对象的key添加引号
quoteProps: 'as-needed'
# jsx中使用单引号
jsxSingleQuote: true
# 多行时尽可能打印尾随逗号
trailingComma: 'all'
# 是否在对象前后添加空格-eg: { foo: bar }
bracketSpacing: false
# 多属性html标签的‘>’折行放置
jsxBracketSameLine: true
# ‘always’单参数箭头函数参数周围使用圆括号-eg: (x) => x  | 'avoid‘:不用
arrowParens: 'always'
# 无需顶部注释即可格式化
requirePragma: false
# 在已被preitter格式化的文件顶部加上标注
insertPragma: false
# 指定在 Markdown 文本的换行方式。选项：`always`──超过 print-width 时换行、 `never`──不换行、 `preserve`──不进行任何操作，保持原样
proseWrap: 'preserve'
# 对HTML全局空白不敏感
htmlWhitespaceSensitivity: 'ignore'
# 不对vue中的script及style标签缩进
vueIndentScriptAndStyle: false
# 结束行形式
endOfLine: 'lf'
# 对引用代码进行格式化
embeddedLanguageFormatting: 'auto'
# 元素的属性每个占一行 --> false ：只有太长才会换行
singleAttributePerLine: false
