#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


TIPS_MSG="commit编写不规范，规范参见: Angular Git Commit Guidelines"
INPUT_FILE="$1"

# 阻止指令输出内容
if npx validate-commit-msg "$(cat "$INPUT_FILE")" > /dev/null 2>&1; then
  exit 0
else 
  echo "$TIPS_MSG"
  exit 1
fi